version: "3.8"

services:
  gateway:
    image: nginx:alpine
    container_name: gateway-container
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cryptosim-global-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-container
    networks:
      - cryptosim-global-network

networks:
  cryptosim-global-network:
    external: true
