
services:
  # -----------------------------
  # 1. GATEWAY
  # -----------------------------
  gateway:
    image: nginx:alpine
    container_name: gateway-container
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - shared-network  # Connects to the backend's network

  # -----------------------------
  # 2. FRONTEND
  # -----------------------------
  frontend:
    build: ./client
    container_name: frontend-container
    networks:
      - shared-network

# -----------------------------
# THE GLUE
# -----------------------------
networks:
  shared-network:
    external: true
    name: cryptosim-global-network # MUST match the name in Step 1
